---
title: "Publish and push to Synapse"
output:
  html_document:
    df_print: paged
---


# Export crosstabs to txt file and push to synapse

```{r}
library(amlresistancenetworks)
library(dplyr)

library(reticulate)
syn = reticulate::import("synapseclient")
sync = syn$login()
```

```{r}
library(MSnbase)

load("data/msnset_global_gene_uncorrected.RData")
exprs(m) <- signif(exprs(m), 3)
write.table(exprs(m), file="data/PTRC_Ex17_crosstabGlobal_gene_uncorrected.txt",
            quote=F, sep="\t")

synTableUpdate(exprs(m), "syn25681584")
```

```{r}
load("data/msnset_global_gene_corrected.RData")
exprs(m) <- signif(exprs(m), 3)
write.table(exprs(m), file="data/PTRC_Ex17_crosstabGlobal_gene_batchCorrected.txt",
            quote=F, sep="\t")
synTableUpdate(exprs(m), "syn25681591")
```

```{r}
load("data/msnset_global_peptide_uncorrected.RData")
exprs(m) <- signif(exprs(m), 3)
write.table(exprs(m), file="data/PTRC_Ex17_crosstabGlobal_peptide_uncorrected.txt",
            quote=F, sep="\t")
synTableUpdate(exprs(m), "syn25681589")
```

```{r}
load("data/msnset_global_peptide_corrected.RData")
exprs(m) <- signif(exprs(m), 3)
write.table(exprs(m), file="data/PTRC_Ex17_crosstabGlobal_peptide_batchCorrected.txt",
            quote=F, sep="\t")
synTableUpdate(exprs(m), "syn25681586")
```

# Push to synapse

